(cl:in-package blockChainPack_-msg)
(cl:export '(SBLOCKTIMESTAMP-VAL
          SBLOCKTIMESTAMP
          SBLOCKTRANS-VAL
          SBLOCKTRANS
          SBLOCKPRODUCTCODE-VAL
          SBLOCKPRODUCTCODE
          SBLOCKHASH-VAL
          SBLOCKHASH
          SBLOCKPREVIOUSHASH-VAL
          SBLOCKPREVIOUSHASH
          SCARRIERNUMBER-VAL
          SCARRIERNUMBER
          FIRSTINDEX-VAL
          FIRSTINDEX
          SECONDINDEX-VAL
          SECONDINDEX
          THIRDINDEX-VAL
          THIRDINDEX
))