// Generated by gencpp from file blockChainPack_/blockDetail.msg
// DO NOT EDIT!


#ifndef BLOCKCHAINPACK__MESSAGE_BLOCKDETAIL_H
#define BLOCKCHAINPACK__MESSAGE_BLOCKDETAIL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace blockChainPack_
{
template <class ContainerAllocator>
struct blockDetail_
{
  typedef blockDetail_<ContainerAllocator> Type;

  blockDetail_()
    : blockNumber(0)
    , productNumber(0)
    , timeStamp()
    , station()
    , serialNumber()
    , blockHash()
    , previousHash()  {
    }
  blockDetail_(const ContainerAllocator& _alloc)
    : blockNumber(0)
    , productNumber(0)
    , timeStamp(_alloc)
    , station(_alloc)
    , serialNumber(_alloc)
    , blockHash(_alloc)
    , previousHash(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _blockNumber_type;
  _blockNumber_type blockNumber;

   typedef int64_t _productNumber_type;
  _productNumber_type productNumber;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _timeStamp_type;
  _timeStamp_type timeStamp;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _station_type;
  _station_type station;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _serialNumber_type;
  _serialNumber_type serialNumber;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _blockHash_type;
  _blockHash_type blockHash;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _previousHash_type;
  _previousHash_type previousHash;





  typedef boost::shared_ptr< ::blockChainPack_::blockDetail_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::blockChainPack_::blockDetail_<ContainerAllocator> const> ConstPtr;

}; // struct blockDetail_

typedef ::blockChainPack_::blockDetail_<std::allocator<void> > blockDetail;

typedef boost::shared_ptr< ::blockChainPack_::blockDetail > blockDetailPtr;
typedef boost::shared_ptr< ::blockChainPack_::blockDetail const> blockDetailConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::blockChainPack_::blockDetail_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::blockChainPack_::blockDetail_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace blockChainPack_

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'blockChainPack_': ['/home/ros/blockChainGit/00blockChain_ws/src/blockChainPack_/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::blockChainPack_::blockDetail_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::blockChainPack_::blockDetail_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::blockChainPack_::blockDetail_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::blockChainPack_::blockDetail_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::blockChainPack_::blockDetail_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::blockChainPack_::blockDetail_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::blockChainPack_::blockDetail_<ContainerAllocator> >
{
  static const char* value()
  {
    return "091c883f51da1788c7811b429bd9b8be";
  }

  static const char* value(const ::blockChainPack_::blockDetail_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x091c883f51da1788ULL;
  static const uint64_t static_value2 = 0xc7811b429bd9b8beULL;
};

template<class ContainerAllocator>
struct DataType< ::blockChainPack_::blockDetail_<ContainerAllocator> >
{
  static const char* value()
  {
    return "blockChainPack_/blockDetail";
  }

  static const char* value(const ::blockChainPack_::blockDetail_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::blockChainPack_::blockDetail_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 blockNumber\n\
int64 productNumber\n\
string timeStamp\n\
string station\n\
string serialNumber\n\
string blockHash\n\
string previousHash\n\
";
  }

  static const char* value(const ::blockChainPack_::blockDetail_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::blockChainPack_::blockDetail_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.blockNumber);
      stream.next(m.productNumber);
      stream.next(m.timeStamp);
      stream.next(m.station);
      stream.next(m.serialNumber);
      stream.next(m.blockHash);
      stream.next(m.previousHash);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct blockDetail_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::blockChainPack_::blockDetail_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::blockChainPack_::blockDetail_<ContainerAllocator>& v)
  {
    s << indent << "blockNumber: ";
    Printer<int64_t>::stream(s, indent + "  ", v.blockNumber);
    s << indent << "productNumber: ";
    Printer<int64_t>::stream(s, indent + "  ", v.productNumber);
    s << indent << "timeStamp: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.timeStamp);
    s << indent << "station: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.station);
    s << indent << "serialNumber: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.serialNumber);
    s << indent << "blockHash: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.blockHash);
    s << indent << "previousHash: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.previousHash);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLOCKCHAINPACK__MESSAGE_BLOCKDETAIL_H
