// Generated by gencpp from file blockChainPack_/finish.msg
// DO NOT EDIT!


#ifndef BLOCKCHAINPACK__MESSAGE_FINISH_H
#define BLOCKCHAINPACK__MESSAGE_FINISH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace blockChainPack_
{
template <class ContainerAllocator>
struct finish_
{
  typedef finish_<ContainerAllocator> Type;

  finish_()
    : compFiles(0)  {
    }
  finish_(const ContainerAllocator& _alloc)
    : compFiles(0)  {
  (void)_alloc;
    }



   typedef int64_t _compFiles_type;
  _compFiles_type compFiles;





  typedef boost::shared_ptr< ::blockChainPack_::finish_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::blockChainPack_::finish_<ContainerAllocator> const> ConstPtr;

}; // struct finish_

typedef ::blockChainPack_::finish_<std::allocator<void> > finish;

typedef boost::shared_ptr< ::blockChainPack_::finish > finishPtr;
typedef boost::shared_ptr< ::blockChainPack_::finish const> finishConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::blockChainPack_::finish_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::blockChainPack_::finish_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace blockChainPack_

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'blockChainPack_': ['/home/pi/blockChainGit/00blockChain_ws/src/blockChainPack_/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::blockChainPack_::finish_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::blockChainPack_::finish_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::blockChainPack_::finish_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::blockChainPack_::finish_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::blockChainPack_::finish_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::blockChainPack_::finish_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::blockChainPack_::finish_<ContainerAllocator> >
{
  static const char* value()
  {
    return "32144edba68833e7b59cc9286ebcccc6";
  }

  static const char* value(const ::blockChainPack_::finish_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x32144edba68833e7ULL;
  static const uint64_t static_value2 = 0xb59cc9286ebcccc6ULL;
};

template<class ContainerAllocator>
struct DataType< ::blockChainPack_::finish_<ContainerAllocator> >
{
  static const char* value()
  {
    return "blockChainPack_/finish";
  }

  static const char* value(const ::blockChainPack_::finish_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::blockChainPack_::finish_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 compFiles\n\
";
  }

  static const char* value(const ::blockChainPack_::finish_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::blockChainPack_::finish_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.compFiles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct finish_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::blockChainPack_::finish_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::blockChainPack_::finish_<ContainerAllocator>& v)
  {
    s << indent << "compFiles: ";
    Printer<int64_t>::stream(s, indent + "  ", v.compFiles);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLOCKCHAINPACK__MESSAGE_FINISH_H
