// Generated by gencpp from file blockChainPack_/nodeOnlineMsg.msg
// DO NOT EDIT!


#ifndef BLOCKCHAINPACK__MESSAGE_NODEONLINEMSG_H
#define BLOCKCHAINPACK__MESSAGE_NODEONLINEMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace blockChainPack_
{
template <class ContainerAllocator>
struct nodeOnlineMsg_
{
  typedef nodeOnlineMsg_<ContainerAllocator> Type;

  nodeOnlineMsg_()
    : nodeName()  {
    }
  nodeOnlineMsg_(const ContainerAllocator& _alloc)
    : nodeName(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _nodeName_type;
  _nodeName_type nodeName;





  typedef boost::shared_ptr< ::blockChainPack_::nodeOnlineMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::blockChainPack_::nodeOnlineMsg_<ContainerAllocator> const> ConstPtr;

}; // struct nodeOnlineMsg_

typedef ::blockChainPack_::nodeOnlineMsg_<std::allocator<void> > nodeOnlineMsg;

typedef boost::shared_ptr< ::blockChainPack_::nodeOnlineMsg > nodeOnlineMsgPtr;
typedef boost::shared_ptr< ::blockChainPack_::nodeOnlineMsg const> nodeOnlineMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::blockChainPack_::nodeOnlineMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::blockChainPack_::nodeOnlineMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace blockChainPack_

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'blockChainPack_': ['/home/ros/blockChainGit/00blockChain_ws/src/blockChainPack_/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::blockChainPack_::nodeOnlineMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::blockChainPack_::nodeOnlineMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::blockChainPack_::nodeOnlineMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::blockChainPack_::nodeOnlineMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::blockChainPack_::nodeOnlineMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::blockChainPack_::nodeOnlineMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::blockChainPack_::nodeOnlineMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fa90f177c62ffd4f5a57999c98f4104f";
  }

  static const char* value(const ::blockChainPack_::nodeOnlineMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfa90f177c62ffd4fULL;
  static const uint64_t static_value2 = 0x5a57999c98f4104fULL;
};

template<class ContainerAllocator>
struct DataType< ::blockChainPack_::nodeOnlineMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "blockChainPack_/nodeOnlineMsg";
  }

  static const char* value(const ::blockChainPack_::nodeOnlineMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::blockChainPack_::nodeOnlineMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string nodeName\n\
";
  }

  static const char* value(const ::blockChainPack_::nodeOnlineMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::blockChainPack_::nodeOnlineMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nodeName);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct nodeOnlineMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::blockChainPack_::nodeOnlineMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::blockChainPack_::nodeOnlineMsg_<ContainerAllocator>& v)
  {
    s << indent << "nodeName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.nodeName);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLOCKCHAINPACK__MESSAGE_NODEONLINEMSG_H
