// Generated by gencpp from file blockChainPack_/stringarray.msg
// DO NOT EDIT!


#ifndef BLOCKCHAINPACK__MESSAGE_STRINGARRAY_H
#define BLOCKCHAINPACK__MESSAGE_STRINGARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace blockChainPack_
{
template <class ContainerAllocator>
struct stringarray_
{
  typedef stringarray_<ContainerAllocator> Type;

  stringarray_()
    : blocks()  {
    }
  stringarray_(const ContainerAllocator& _alloc)
    : blocks(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _blocks_type;
  _blocks_type blocks;





  typedef boost::shared_ptr< ::blockChainPack_::stringarray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::blockChainPack_::stringarray_<ContainerAllocator> const> ConstPtr;

}; // struct stringarray_

typedef ::blockChainPack_::stringarray_<std::allocator<void> > stringarray;

typedef boost::shared_ptr< ::blockChainPack_::stringarray > stringarrayPtr;
typedef boost::shared_ptr< ::blockChainPack_::stringarray const> stringarrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::blockChainPack_::stringarray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::blockChainPack_::stringarray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace blockChainPack_

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'blockChainPack_': ['/home/ros/blockChainGit/00blockChain_ws/src/blockChainPack_/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::blockChainPack_::stringarray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::blockChainPack_::stringarray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::blockChainPack_::stringarray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::blockChainPack_::stringarray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::blockChainPack_::stringarray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::blockChainPack_::stringarray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::blockChainPack_::stringarray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bbe9b96b676128983188b5e1fc353be9";
  }

  static const char* value(const ::blockChainPack_::stringarray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbbe9b96b67612898ULL;
  static const uint64_t static_value2 = 0x3188b5e1fc353be9ULL;
};

template<class ContainerAllocator>
struct DataType< ::blockChainPack_::stringarray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "blockChainPack_/stringarray";
  }

  static const char* value(const ::blockChainPack_::stringarray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::blockChainPack_::stringarray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8[] blocks\n\
";
  }

  static const char* value(const ::blockChainPack_::stringarray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::blockChainPack_::stringarray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.blocks);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct stringarray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::blockChainPack_::stringarray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::blockChainPack_::stringarray_<ContainerAllocator>& v)
  {
    s << indent << "blocks[]" << std::endl;
    for (size_t i = 0; i < v.blocks.size(); ++i)
    {
      s << indent << "  blocks[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.blocks[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLOCKCHAINPACK__MESSAGE_STRINGARRAY_H
