// Generated by gencpp from file blockChainPack_/Test.msg
// DO NOT EDIT!


#ifndef BLOCKCHAINPACK__MESSAGE_TEST_H
#define BLOCKCHAINPACK__MESSAGE_TEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace blockChainPack_
{
template <class ContainerAllocator>
struct Test_
{
  typedef Test_<ContainerAllocator> Type;

  Test_()
    : testingMsg()  {
    }
  Test_(const ContainerAllocator& _alloc)
    : testingMsg(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _testingMsg_type;
  _testingMsg_type testingMsg;





  typedef boost::shared_ptr< ::blockChainPack_::Test_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::blockChainPack_::Test_<ContainerAllocator> const> ConstPtr;

}; // struct Test_

typedef ::blockChainPack_::Test_<std::allocator<void> > Test;

typedef boost::shared_ptr< ::blockChainPack_::Test > TestPtr;
typedef boost::shared_ptr< ::blockChainPack_::Test const> TestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::blockChainPack_::Test_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::blockChainPack_::Test_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace blockChainPack_

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'blockChainPack_': ['/home/ros/blockChainGit/00blockChain_ws/src/blockChainPack_/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::blockChainPack_::Test_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::blockChainPack_::Test_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::blockChainPack_::Test_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::blockChainPack_::Test_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::blockChainPack_::Test_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::blockChainPack_::Test_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::blockChainPack_::Test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "78c90679f25a95e5f459c98217d5f15a";
  }

  static const char* value(const ::blockChainPack_::Test_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x78c90679f25a95e5ULL;
  static const uint64_t static_value2 = 0xf459c98217d5f15aULL;
};

template<class ContainerAllocator>
struct DataType< ::blockChainPack_::Test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "blockChainPack_/Test";
  }

  static const char* value(const ::blockChainPack_::Test_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::blockChainPack_::Test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string testingMsg\n\
";
  }

  static const char* value(const ::blockChainPack_::Test_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::blockChainPack_::Test_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.testingMsg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Test_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::blockChainPack_::Test_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::blockChainPack_::Test_<ContainerAllocator>& v)
  {
    s << indent << "testingMsg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.testingMsg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLOCKCHAINPACK__MESSAGE_TEST_H
